"""Add deep research fields to messages

Revision ID: 2afcf054549b
Revises: 5073572e3680
Create Date: 2025-09-11 09:57:38.100002

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision = '2afcf054549b'
down_revision = '5073572e3680'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    connection = op.get_bind()
    inspector = inspect(connection)

    def safe_drop_index(index_name, table_name):
        indexes = [idx['name'] for idx in inspector.get_indexes(table_name)]
        if index_name in indexes:
            op.drop_index(index_name, table_name=table_name)

    safe_drop_index('idx_chats_created_at', table_name='chats')
    safe_drop_index('idx_chats_updated_at', table_name='chats')
    safe_drop_index('idx_document_chunks_chunk_index', table_name='document_chunks')
    safe_drop_index('idx_document_chunks_document_id', table_name='document_chunks')
    safe_drop_index('idx_documents_created_at', table_name='documents')
    safe_drop_index('idx_documents_file_type', table_name='documents')
    op.add_column('messages', sa.Column('is_deep_research', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('messages', sa.Column('deep_research_status', sa.String(length=20), nullable=True, server_default='pending'))
    op.add_column('messages', sa.Column('deep_research_params', sa.Text(), nullable=True))
    op.add_column('messages', sa.Column('deep_research_error', sa.Text(), nullable=True))
    safe_drop_index('idx_messages_chat_id', table_name='messages')
    safe_drop_index('idx_messages_created_at', table_name='messages')
    safe_drop_index('idx_messages_role', table_name='messages')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_messages_role', 'messages', ['role'], unique=False)
    op.create_index('idx_messages_created_at', 'messages', ['created_at'], unique=False)
    op.create_index('idx_messages_chat_id', 'messages', ['chat_id'], unique=False)
    op.drop_column('messages', 'deep_research_error')
    op.drop_column('messages', 'deep_research_params')
    op.drop_column('messages', 'deep_research_status')
    op.drop_column('messages', 'is_deep_research')
    op.create_index('idx_documents_file_type', 'documents', ['file_type'], unique=False)
    op.create_index('idx_documents_created_at', 'documents', ['created_at'], unique=False)
    op.create_index('idx_document_chunks_document_id', 'document_chunks', ['document_id'], unique=False)
    op.create_index('idx_document_chunks_chunk_index', 'document_chunks', ['chunk_index'], unique=False)
    op.create_index('idx_chats_updated_at', 'chats', ['updated_at'], unique=False)
    op.create_index('idx_chats_created_at', 'chats', ['created_at'], unique=False)
    # ### end Alembic commands ###
