"""Add citation mapping and document references to messages

Revision ID: 5073572e3680
Revises: add_email_verification
Create Date: 2025-09-05 15:14:32.829797

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5073572e3680'
down_revision = 'add_email_verification'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chats', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_index('idx_document_tags_document', table_name='document_tags')
    op.drop_index('idx_document_tags_tag', table_name='document_tags')
    op.alter_column('documents', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('email_resend_tracking', 'attempt_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('email_verifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.add_column('messages', sa.Column('citation_mapping', sa.Text(), nullable=True))
    op.add_column('messages', sa.Column('document_references', sa.Text(), nullable=True))
    op.alter_column('tags', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_index('idx_tags_name', table_name='tags')
    op.drop_constraint('uq_tags_user_id_name', 'tags', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_tags_user_id_name', 'tags', ['user_id', 'name'])
    op.create_index('idx_tags_name', 'tags', ['name'], unique=False)
    op.alter_column('tags', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('messages', 'document_references')
    op.drop_column('messages', 'citation_mapping')
    op.alter_column('email_verifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('email_resend_tracking', 'attempt_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('documents', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index('idx_document_tags_tag', 'document_tags', ['tag_id'], unique=False)
    op.create_index('idx_document_tags_document', 'document_tags', ['document_id'], unique=False)
    op.alter_column('chats', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###