"""Initial schema with vector support

Revision ID: a5fd321b15b5
Revises: 
Create Date: 2025-08-07 09:27:51.998811

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision = 'a5fd321b15b5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Get database connection and inspector
    connection = op.get_bind()
    inspector = inspect(connection)
    
    # Helper function to safely drop index
    def safe_drop_index(index_name, table_name):
        indexes = [idx['name'] for idx in inspector.get_indexes(table_name)]
        if index_name in indexes:
            op.drop_index(index_name, table_name=table_name)
    
    # Helper function to safely drop constraint
    def safe_drop_constraint(constraint_name, table_name):
        foreign_keys = inspector.get_foreign_keys(table_name)
        if any(fk['name'] == constraint_name for fk in foreign_keys):
            op.drop_constraint(constraint_name, table_name, type_='foreignkey')
    
    # Safely drop indexes if they exist
    safe_drop_index('idx_chats_created_at', 'chats')
    safe_drop_index('idx_chats_updated_at', 'chats')
    safe_drop_index('idx_document_chunks_chunk_index', 'document_chunks')
    safe_drop_index('idx_document_chunks_document_id', 'document_chunks')
    safe_drop_constraint('document_chunks_document_id_fkey', 'document_chunks')
    op.create_foreign_key(None, 'document_chunks', 'documents', ['document_id'], ['id'])
    safe_drop_index('idx_documents_created_at', 'documents')
    safe_drop_index('idx_documents_file_type', 'documents')
    safe_drop_index('idx_messages_chat_id', 'messages')
    safe_drop_index('idx_messages_created_at', 'messages')
    safe_drop_index('idx_messages_role', 'messages')
    safe_drop_constraint('messages_chat_id_fkey', 'messages')
    op.create_foreign_key(None, 'messages', 'chats', ['chat_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key('messages_chat_id_fkey', 'messages', 'chats', ['chat_id'], ['id'], ondelete='CASCADE')
    op.create_index('idx_messages_role', 'messages', ['role'], unique=False)
    op.create_index('idx_messages_created_at', 'messages', ['created_at'], unique=False)
    op.create_index('idx_messages_chat_id', 'messages', ['chat_id'], unique=False)
    op.create_index('idx_documents_file_type', 'documents', ['file_type'], unique=False)
    op.create_index('idx_documents_created_at', 'documents', ['created_at'], unique=False)
    op.drop_constraint(None, 'document_chunks', type_='foreignkey')
    op.create_foreign_key('document_chunks_document_id_fkey', 'document_chunks', 'documents', ['document_id'], ['id'], ondelete='CASCADE')
    op.create_index('idx_document_chunks_document_id', 'document_chunks', ['document_id'], unique=False)
    op.create_index('idx_document_chunks_chunk_index', 'document_chunks', ['chunk_index'], unique=False)
    op.create_index('idx_chats_updated_at', 'chats', ['updated_at'], unique=False)
    op.create_index('idx_chats_created_at', 'chats', ['created_at'], unique=False)
    # ### end Alembic commands ###