"""Remove server defaults from deep research fields

Revision ID: f13a764bb6fe
Revises: 2afcf054549b
Create Date: 2025-09-11 10:21:31.876281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f13a764bb6fe'
down_revision = '2afcf054549b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###